package hib;
// Generated Dec 10, 2019 6:00:16 PM by Hibernate Tools 4.3.5.Final

/**
 * Administrators generated by hbm2java
 */
public class Administrators implements java.io.Serializable {

	private int adminid;
	private String username;
	private String password;

	public Administrators() {
	}

	public Administrators(int adminid) {
		this.adminid = adminid;
	}

	public Administrators(int adminid, String username, String password) {
		this.adminid = adminid;
		this.username = username;
		this.password = password;
	}

	public int getAdminid() {
		return this.adminid;
	}

	public void setAdminid(int adminid) {
		this.adminid = adminid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
