package hib;
// Generated Dec 10, 2019 6:00:16 PM by Hibernate Tools 4.3.5.Final

/**
 * Loginlog generated by hbm2java
 */
public class Loginlog implements java.io.Serializable {

	private LoginlogId id;
	private Users users;

	public Loginlog() {
	}

	public Loginlog(LoginlogId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public LoginlogId getId() {
		return this.id;
	}

	public void setId(LoginlogId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
