package hib;
// Generated Dec 15, 2019 4:59:16 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

/**
 * LoginlogId generated by hbm2java
 */
public class LoginlogId implements java.io.Serializable {

	private int userid;
	private Serializable logintime;

	public LoginlogId() {
	}

	public LoginlogId(int userid, Serializable logintime) {
		this.userid = userid;
		this.logintime = logintime;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Serializable getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Serializable logintime) {
		this.logintime = logintime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginlogId))
			return false;
		LoginlogId castOther = (LoginlogId) other;

		return (this.getUserid() == castOther.getUserid())
				&& ((this.getLogintime() == castOther.getLogintime()) || (this.getLogintime() != null
						&& castOther.getLogintime() != null && this.getLogintime().equals(castOther.getLogintime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + (getLogintime() == null ? 0 : this.getLogintime().hashCode());
		return result;
	}

}
