package hib;
// Generated Dec 15, 2019 4:59:16 PM by Hibernate Tools 4.3.5.Final

/**
 * SimilarityId generated by hbm2java
 */
public class SimilarityId implements java.io.Serializable {

	private int mid1;
	private int mid2;

	public SimilarityId() {
	}

	public SimilarityId(int mid1, int mid2) {
		this.mid1 = mid1;
		this.mid2 = mid2;
	}

	public int getMid1() {
		return this.mid1;
	}

	public void setMid1(int mid1) {
		this.mid1 = mid1;
	}

	public int getMid2() {
		return this.mid2;
	}

	public void setMid2(int mid2) {
		this.mid2 = mid2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SimilarityId))
			return false;
		SimilarityId castOther = (SimilarityId) other;

		return (this.getMid1() == castOther.getMid1()) && (this.getMid2() == castOther.getMid2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMid1();
		result = 37 * result + this.getMid2();
		return result;
	}

}
